### PR TITLE
fix(typo): added a missing word

### PR DESCRIPTION
**Pull request by siddharthkhonde**
## Feature or Problem
Typo fix in "https://wasmcloud.com/docs/tour/why-wasmcloud" 

### Manual Verification
deployed the site locally and manually tested the change

### CODE REVIEW

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]
Hey @siddharthkhonde ! I actually think this part is correct, albeit a possibly run-on sentence. The idea is that the biggest benefits of wasmCloud come after you've built your app, which matches what the last sentence there says. Perhaps it could be a little cleaner, what about:
```
- Beyond providing an easy-to-use platform that's quick to get started with, we also want to make sure that you understand that the biggest benefits of wasmCloud come after you've built your application.
+ wasmCloud is an easy-to-use platform that's quick to get started with, which is essential for a good developer experience, and this project extends far beyond "Hello World." This page emphasizes the intention behind the design of wasmCloud, and the benefits that follow after you've built your application.
```

Thank you so much for taking a look at this piece of language and calling it out as something that can be more clear!

**Comment by siddharthkhonde** [comment]
> wasmCloud is an easy-to-use platform that's quick to get started with, which is essential for a good developer experience, and this project extends far beyond "Hello World." This page emphasizes the intention behind the design of wasmCloud, and the benefits that follow after you've built your application.

this actually looks much better and well-articulated. let me update the PR :)

**Review by lachieh — APPROVED** [review]
Thank you! Looks like you just need to sign your commit and force push and then it can merge. [Instructions are on the test.](https://github.com/wasmCloud/wasmcloud.com/pull/328/checks?check_run_id=22760304342)

**Comment by siddharthkhonde** [comment]
> Thank you! Looks like you just need to sign your commit and force push and then it can merge. [Instructions are on the test.](https://github.com/wasmCloud/wasmcloud.com/pull/328/checks?check_run_id=22760304342)

Hi @lachieh , thank you so much for the approval. I have amended the commits. kindly advise if it looks good now :)

**Review by brooksmtownsend — APPROVED** [review]

**Pull request merged**
