### PR TITLE
Favicon

### LINKED ISSUE #3: favicon not showing in search results
Screen Shot 2021-04-14 at 9 14 32 AM

### PR DESCRIPTION
**Pull request by jordan-rash**
Fixes #3 

There were more than 1 way to fix this.  It looks like the theme was written to look for `favicon.png` instead of `favicon.ico`.  This didnt feel right to me, so I edited the partial.  If it is preferred to not edit the theme code, then we could just add `favicon.png` to the static directory and call it a day.

### CODE REVIEW

**Review by autodidaddict — CHANGES_REQUESTED** [review]
Couple of points. Editing the theme doesn't actually edit what gets rendered. If you want to change that partial, then you need to copy the `themes/.../layouts/...file` into the `layouts` directory of the main repository.

Because this is relatively annoying to do, my vote is for just dropping all of the favicon variants into static and calling it a day.

**Comment by jordan-rash** [comment]
> Couple of points. Editing the theme doesn't actually edit what gets rendered. If you want to change that partial, then you need to copy the `themes/.../layouts/...file` into the `layouts` directory of the main repository.

I might be misunderstanding what you are saying @autodidaddict...are you saying that the current edits dont change the render?  When I look at the code in the netlify deploy preview, it appears to have pulled the edits though. 
```html
<link rel="shortcut icon" href=https://deploy-preview-4--dreamy-golick-5f201e.netlify.app/images/favicon.ico type=image/x-icon>
<link rel="shortcut icon" href=https://deploy-preview-4--dreamy-golick-5f201e.netlify.app/images/favicon.ico type=image/vnd.microsoft.icon>
<link rel=icon href=https://deploy-preview-4--dreamy-golick-5f201e.netlify.app/images/favicon.ico type=image/x-icon>
```

Or are you saying that I should have copied it into the `layouts` directory so that it over-rode the theme default and not touched the one in the `themes/` directory?  Not that it matters (I am more curious for future Hugo edits), I think that I agree with just moving a `favicon.png` into the static directory and calling it a day.  Thanks!!

**Comment by jordan-rash** [comment]
Reverted and back to the original.  The favicon.png is rendering as expected :-)
```html
<link rel="shortcut icon" href=https://deploy-preview-4--dreamy-golick-5f201e.netlify.app/images/favicon.png type=image/x-icon>
```

**Comment by autodidaddict** [comment]
I wonder if this behavior is theme dependent or version related. On my own site changes made in the themes folder don't render and I have to create and override. :thinking_face:

**Review by autodidaddict — APPROVED** [review]

**Review by brooksmtownsend — APPROVED** [review]
i see the icon :)

**Pull request merged**
