### PR TITLE
chore: clarify about the usage of provider word

### PR DESCRIPTION
**Pull request by yordis**

### CODE REVIEW

**Comment by LiamRandall** [comment]
lgtm

**Review by thomastaylor312 — APPROVED** [review]
Thanks for helping clarify this!

**Comment by thomastaylor312** [comment]
@yordis Can you please sign your commit? After that I can go ahead and merge. If you haven't signed a commit for DCO before, the GH check has some [helpful instructions](https://github.com/wasmCloud/wasmcloud.com-dev/pull/150/checks?check_run_id=16197595458)!

**Comment by yordis** [comment]
done ✅

**Pull request merged**
