### PR TITLE
feat(*)!: Various small doc updates

### PR DESCRIPTION
**Pull request by thomastaylor312**
This update has 3 separate commits that addresses 3 small missing or out of date pieces of information:

- Removed reference to bindle
- Updated status names in wadm docs
- Added documentation to the control interface for actor config

### CODE REVIEW

**Review by connorsmith256 — APPROVED** [review]

**Comment by lachieh** [comment]
noooo

**Comment by lachieh** [comment]
Submit another PR to add redirects for the deleted pages, please.

**Comment by lachieh** [comment]
@thomastaylor312 find somewhere else to redirect all these pages:
- docs/deployment/oci/bindle
- docs/deployment/oci/bindle/actor-bindles
- docs/deployment/oci/bindle/provider-bindles
- docs/deployment/oci/bindle/using-bindles

**Comment by thomastaylor312** [comment]
Done in #236

**Pull request merged**
