### PR TITLE
[WIP] First pass at wasmcloud.com proposed content

### PR DESCRIPTION
**Pull request by LiamRandall**
Lots of feedback needed on here:
- home: header hero image
- home: capabilities word cloud, replace images with font awesome
- about: wordsmithing Mission & Vision
- about: template pictures
- contact: mailing list

- blog:

### CODE REVIEW

**Comment by autodidaddict** [comment]
From our discussion earlier:
* change the pulsing video hero image to the wasmcloud logo (for now)
* change all the placeholder images in the "how does it work" to either be blank or the wasmcloud logo (for now)
* landing page, `seperate` misspelled, should be `separate`
* `Rapid development` view more link should go to https://wasmcloud.dev/app-dev/getting-started/
* polyglot platform text needs to go. Maybe replace with `Building on the polyglot power of WebAssembly, you can create actors in AssemblyScript, TinyGo, or Rust` You could change that image to a collage of supported language logos.
* `Pleasently portable` is misspelled, should be `pleasantly` - change that image to some icons for browsers, servers, IoT devices, etc. you can probably get these from font awesome too, but the key thing is they need to have consistent design treatment. they can't look like a newspaper ransom letter.
* Completely connected - some nice clip art here of a network graph will do nicely, also easily create-able ourselves using the wasmCloud design guidelines and some basic "edges and nodes" illustration
* Securely Scalable - either blank the image or use some nice treatment of a padlock or something else a "security placeholder"
* Integrate the capabilities you already use - per discussion, change that "wheel" of icons to something like font awesome icons. Maybe change "configured" to "equipped"

**Comment by autodidaddict** [comment]
Actually I think a good image for the `Completely connected` section on the landing page might be the one that's on the wasmcloud linkedin header: 
image

**Comment by brooksmtownsend** [comment]
Agreed w/ @autodidaddict on those points, the only other one that I can offer is that we should tidy up the capabilities icons to better fit their bubbles. If the format is going to change to the wheel we should do it then but as of now some extend past the bubble, I'd be happy to help trim and make them transparent if needed

**Comment by LiamRandall** [comment]
@brooksmtownsend we had a solid discussion this morning about just leveraging the font awesome icons, so we'll be doing that.  I have a few pro subscriptions I can share to help speed this along a bit.

@autodidaddict good call on reusing that image.

**Comment by autodidaddict** [comment]
All the graphics/icons that I can see in this PR look good enough for placeholders on the landing page.

**Comment by brooksmtownsend** [comment]
Oh also @LiamRandall , on the about page for `First Party Interfaces` we actually have 15 out, but if you wanted to have it as `First party languages` then I think 3 is accurate

**Comment by autodidaddict** [comment]
@LiamRandall @brooksmtownsend that phrasing where we show the 3 languages should be `Supported Languages`, as there's nothing first party about our language support. So, either `First Party Capability Providers` or `Supported Languages`, as they're very different things.

**Comment by autodidaddict** [comment]
The "how it works" link should point to `wasmcloud.dev` and not to the scaffolded how it works content here.

**Comment by LiamRandall** [comment]
Responded to all items.

**Pull request closed without merging**
