### PR TITLE
Add woke for checking our language use

### PR DESCRIPTION
**Pull request by joonas**
## Feature or Problem

In setting up #406, I got to wondering if there was a way to better automate this, and came across [Microsoft's Inclusive Linting guidance](https://microsoft.github.io/code-with-engineering-playbook/continuous-integration/inclusive-linting/), which recommends adopting [`woke`](https://github.com/get-woke/woke).

This seems like a reasonable first step towards more inclusive language use, so I put together a PR to install `woke` from source (as opposed to using the [`woke-action`](https://github.com/get-woke/woke-action) which is pretty out of date at this point) and run it as part of the pipeline, failing if it reports any `error` levels.

## Example failure
Screenshot 2024-05-06 at 9 29 47 AM

### CODE REVIEW

**Comment by joonas** [comment]
Note, this PR also demonstrates how the `woke` failure will look like, since I am not addressing the errors that it reports.

I can address the issues woke highlights, or leave them for a separate PR to do if we'd like to go forward with this approach.

**Review by brooksmtownsend — APPROVED** [review]
Looks great, it seems to give nice output in the actions failures too 😄 @joonas would you mind addressing the warnings so-far? May as well get us on a clean slate as we merge

**Comment by lachieh** [comment]
I like this addition. We initially had the vale tool configured to promote these changes during editing as well. I'm not sure if there's a way to include [this action](https://github.com/errata-ai/vale-action) and enable inclusivity rules there instead?

Is there a way to make one-off exceptions? I can't think of many we'd need, other than pointing out examples of what-not-to-do and perhaps quoting others, but even then we can probably [paraphrase] their words.

**Comment by lachieh** [comment]
It might also be worth considering a more complete linting workflow which includes markdownlint ([related PR](https://github.com/wasmCloud/wasmcloud.com/pull/374)) and eslint (not configured) as well. 

Edit: As it turns out, I already created an issue for that task: wasmCloud/wasmcloud.com#284

**Comment by joonas** [comment]
> I like this addition. We initially had the vale tool configured to promote these changes during editing as well. I'm not sure if there's a way to include [this action](https://github.com/errata-ai/vale-action) and enable inclusivity rules there instead?

It should be possible to turn the [default set of rules from woke](https://github.com/get-woke/woke/blob/main/pkg/rule/default.yaml) into something that `vale` could run instead.

If we'd like to go that direction, I'm happy to take a pass at doing exactly that in this PR and also then include the vale-action as part of a linting workflow - does that lineup with what you were thinking?

> Is there a way to make one-off exceptions? I can't think of many we'd need, other than pointing out examples of what-not-to-do and perhaps quoting others, but even then we can probably [paraphrase] their words.

Assuming we just integrate these rules to Vale, I guess this then becomes a Vale question, which I'd assume there's some form of exception notation for?

On a personal level, I would rather we paraphrase rather than use quotes as-is, if necessary.

**Comment by lachieh** [comment]
> If we'd like to go that direction, I'm happy to take a pass at doing exactly that in this PR and also then include the vale-action as part of a linting workflow - does that lineup with what you were thinking?

Yep, exactly. Then we can expand the linting workflow with other steps in future.

> Assuming we just integrate these rules to Vale, I guess this then becomes a Vale question, which I'd assume there's some form of exception notation for?
> 
> On a personal level, I would rather we paraphrase rather than use quotes as-is, if necessary.

Agreed. Paraphrasing is the solution, in my opinion.

After running vale locally on one of these files, it seems that Vale is quite mad about a number of things even after updating the dictionary from the cosmonic file which has a higher number of words. Some of them are legit catches, though, so it may be worth investigating a way to run Vale for only staged files?

It has rules from the Microsoft Writing Style Guide included, but that doesn't seem to cover inclusive language so we'd still need to do that.

<details><summary>Output of <code>vale blog/wasm-day-summary-blog/index.mdx</code></summary>

```
 16:34   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 16:76   warning     Consider removing 'quickly'.    Microsoft.Adverbs         
 16:97   suggestion  'being adopted' looks like      Microsoft.Passive         
                     passive voice.                                            
 16:191  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 16:213  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'We'.                            
 20:1    suggestion  'Welcome + Opening Remarks      Microsoft.Headings        
                     —Divya Mohan, SUSE' should use                            
                     sentence-style capitalization.                            
 20:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 20:131  warning     'Mohan' is a typo!              wasmCloud.Spelling        
 20:138  warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 22:51   warning     'Rishit' is a typo!             wasmCloud.Spelling        
 22:58   warning     'Dagli' is a typo!              wasmCloud.Spelling        
 22:187  suggestion  'be found' looks like passive   Microsoft.Passive         
                     voice.                                                    
 24:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 24:1    suggestion  'Components, WebAssembly's      Microsoft.Headings        
                     Docker's Moment —Bailey                                   
                     Hayes, Cosmonic' should use                               
                     sentence-style capitalization.                            
 26:207  suggestion  Verify your use of 'She' with   Microsoft.Vocab           
                     the A-Z word list.                                        
 28:30   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 28:48   suggestion  'is broken' looks like passive  Microsoft.Passive         
                     voice.                                                    
 28:59   suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 28:122  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 28:214  error       Use 'that's' instead of 'that   Microsoft.Contractions    
                     is'.                                                      
 28:219  suggestion  'is filled' looks like passive  Microsoft.Passive         
                     voice.                                                    
 28:301  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 28:367  error       Use 'can't' instead of          Microsoft.Contractions    
                     'cannot'.                                                 
 28:374  warning     Consider removing 'easily'.     Microsoft.Adverbs         
 28:444  error       Use 'they're' instead of 'they  Microsoft.Contractions    
                     are'.                                                     
 28:488  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'We'.                            
 28:591  warning     ' strictly-' doesn't need a     Microsoft.Hyphens         
                     hyphen.                                                   
 28:592  warning     Consider removing 'strictly'.   Microsoft.Adverbs         
 28:628  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'We'.                            
 30:49   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 30:102  warning     Consider removing 'really'.     Microsoft.Adverbs         
 30:168  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 30:204  error       Use 'that's' instead of 'that   Microsoft.Contractions    
                     is'.                                                      
 30:272  suggestion  'be picked' looks like passive  Microsoft.Passive         
                     voice.                                                    
 30:339  suggestion  Verify your use of 'she' with   Microsoft.Vocab           
                     the A-Z word list.                                        
 32:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 32:1    suggestion  'Choosing Customizability       Microsoft.Headings        
                     and Distributing Dependencies                             
                     with Wasm Components —Taylor                              
                     Thomas, Cosmonic' should use                              
                     sentence-style capitalization.                            
 34:53   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 34:388  warning     Consider removing               Microsoft.Adverbs         
                     'beautifully'.                                            
 36:166  error       Punctuation should be inside    Microsoft.Quotes          
                     the quotes.                                               
 38:118  error       Use 'isn't' instead of 'is      Microsoft.Contractions    
                     not'.                                                     
 38:128  suggestion  'be missed' looks like passive  Microsoft.Passive         
                     voice.                                                    
 40:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 40:1    suggestion  'Pathfinder to GPU Offload in   Microsoft.Headings        
                     WASM —Atanas Atanasov & Aaron                             
                     Dorney, Intel' should use                                 
                     sentence-style capitalization.                            
 40:19   warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 40:34   warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 40:157  warning     'Dorney' is a typo!             wasmCloud.Spelling        
 42:222  warning     'Speficially' is a typo!        wasmCloud.Spelling        
 42:270  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 44:14   warning     'Adanas' is a typo!             wasmCloud.Spelling        
 44:240  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 44:538  error       Use 'isn't' instead of 'is      Microsoft.Contractions    
                     not'.                                                     
 46:21   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 46:29   warning     'whistlestop' is a typo!        wasmCloud.Spelling        
 46:92   suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 46:293  warning     'transformative' is a typo!     wasmCloud.Spelling        
 48:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 48:1    suggestion  '🌍⚡ Edge Evolution: Orange's  Microsoft.Headings        
                     Edge Strategy with WebAssembly                            
                     & CNCF WasmCloud —Yann                                    
                     Cardon, Orange' should use                                
                     sentence-style capitalization.                            
 48:66   warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 50:1    warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'We'.                            
 52:317  suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 52:776  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 52:778  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 52:820  warning     'telcos' is a typo!             wasmCloud.Spelling        
 52:834  warning     'Yann's' is a typo!             wasmCloud.Spelling        
 54:25   suggestion  'being trialed' looks like      Microsoft.Passive         
                     passive voice.                                            
 54:237  suggestion  'be found' looks like passive   Microsoft.Passive         
                     voice.                                                    
 56:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 56:1    suggestion  'WebAssembly on the Factory     Microsoft.Headings        
                     Floor: Efficient and Secure                               
                     Processing of High Velocity                               
                     Machine Data —Jochen Rau &                                
                     Tyler Schoppe—MachineMetrics,                             
                     LLC' should use sentence-style                            
                     capitalization.                                           
 56:238  warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 58:59   suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 58:88   suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 58:163  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 58:305  error       Use 'it's' instead of 'it is'.  Microsoft.Contractions    
 58:369  suggestion  'is processed' looks like       Microsoft.Passive         
                     passive voice.                                            
 60:148  warning     Consider removing 'closely'.    Microsoft.Adverbs         
 60:156  suggestion  Consider using 'check' or       Microsoft.ComplexWords    
                     'watch' instead of 'monitor'.                             
 60:316  warning     'wasmCloud's' is a typo!        wasmCloud.Spelling        
 62:21   warning     'wasmCloud's' is a typo!        wasmCloud.Spelling        
 62:56   warning     Consider removing 'really'.     Microsoft.Adverbs         
 62:75   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 62:122  warning     Try to avoid using              Microsoft.We              
                     first-person plural like                                  
                     'our'.                                                    
 62:156  suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 62:253  warning     For a general audience, use     Microsoft.GeneralURL      
                     'address' rather than 'URL'.                              
 62:291  suggestion  Consider using 'many' instead   Microsoft.ComplexWords    
                     of 'multiple'.                                            
 62:414  warning     Consider removing 'really'.     Microsoft.Adverbs         
 62:448  warning     Try to avoid using              Microsoft.We              
                     first-person plural like                                  
                     'our'.                                                    
 62:475  warning     Consider removing 'very'.       Microsoft.Adverbs         
 64:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 64:1    suggestion  'CRI-O's WASM Adventure:        Microsoft.Headings        
                     Challenges, Strategies,                                   
                     and What Lies Ahead —Sohan                                
                     Kunkerkar & Peter Hunt, Red                               
                     Hat' should use sentence-style                            
                     capitalization.                                           
 64:5    warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 64:13   warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 64:173  warning     'Kunkerkar' is a typo!          wasmCloud.Spelling        
 66:170  warning     'Sohan' is a typo!              wasmCloud.Spelling        
 66:191  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 66:225  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 68:4    warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 68:104  warning     'Sohan' is a typo!              wasmCloud.Spelling        
 68:126  warning     Consider using 'some' instead   Microsoft.Wordiness       
                     of 'some of the'.                                         
 68:183  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 68:197  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 68:214  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 68:247  suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 68:272  suggestion  Verify your use of 'Above'      Microsoft.Vocab           
                     with the A-Z word list.                                   
 70:1    suggestion  Try to keep sentences short (<  Microsoft.SentenceLength  
                     30 words).                                                
 70:1    warning     'Sohan' is a typo!              wasmCloud.Spelling        
 70:27   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'us'.                            
 70:55   suggestion  Try to simplify this sentence.  Microsoft.Semicolon       
 72:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 72:1    suggestion  'WASI and the Cloud: A          Microsoft.Headings        
                     Game-Changing Duo —Bailey                                 
                     Hayes, Cosmonic & Jiaxiao                                 
                     Zhou, Microsoft' should use                               
                     sentence-style capitalization.                            
 72:5    warning     Avoid using acronyms in a       Microsoft.HeadingAcronyms 
                     title or heading.                                         
 72:14   warning     Prefer 'cloud' over 'the        Microsoft.Terms           
                     Cloud'.                                                   
 74:19   warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 74:207  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.                            
 74:279  warning     Consider removing 'easily'.     Microsoft.Adverbs         
 74:310  suggestion  Use the Oxford comma in         Microsoft.OxfordComma     
                     'different, platforms and                                 
                     solutions.'.                                              
 76:24   warning     Consider removing 'tightly'.    Microsoft.Adverbs         
 76:232  suggestion  'is run' looks like passive     Microsoft.Passive         
                     voice.                                                    
 76:243  warning     Use first person (such as       Microsoft.FirstPerson     
                     'my') sparingly.                                          
 76:293  warning     Use first person (such as       Microsoft.FirstPerson     
                     'my') sparingly.                                          
 76:336  warning     Use first person (such as ' I   Microsoft.FirstPerson     
                     ') sparingly.                                             
 76:400  warning     Use first person (such as ' I   Microsoft.FirstPerson     
                     ') sparingly.                                             
 78:249  suggestion  Consider using 'many' instead   Microsoft.ComplexWords    
                     of 'multiple'.                                            
 78:280  suggestion  Consider using 'many' instead   Microsoft.ComplexWords    
                     of 'multiple'.                                            
 80:14   warning     Consider removing 'really'.     Microsoft.Adverbs         
 82:1    suggestion  'Closing Remarks —Liam          Microsoft.Headings        
                     Randall, Program Committee                                
                     Member' should use                                        
                     sentence-style capitalization.                            
 82:1    error       Remove the spaces around ' —'.  Microsoft.Dashes          
 84:161  warning     Try to avoid using              Microsoft.We              
                     first-person plural like 'we'.      
```

</details>

**Comment by joonas** [comment]
> After running vale locally on one of these files, it seems that Vale is quite mad about a number of things even after updating the dictionary from the cosmonic file which has a higher number of words. Some of them are legit catches, though, so it may be worth investigating a way to run Vale for only staged files?

I think that's a good idea, really the idea is to help the person changing something catch improvements on the use of language.

> It has rules from the Microsoft Writing Style Guide included, but that doesn't seem to cover inclusive language so we'd still need to do that.

I was looking over it as well and didn't see anything, but thankfully it's easy enough to break it out in to custom style we include, either as part of the existing `wasmCloud` style or a new style focused on using inclusive language.

I'll make the suggested changes when I find some time over the next couple of days.

Separately I do think we should look at the changes in #374 and get those merged in, there's a lot of good work being done there.

**Comment by lachieh** [comment]
> I was looking over it as well and didn't see anything, but thankfully it's easy enough to break it out in to custom style we include, either as part of the existing wasmCloud style or a new style focused on using inclusive language.

I'd say the latter as a separate repo and then we can contribute it to the package hub: https://vale.sh/hub/

> I'll make the suggested changes when I find some time over the next couple of days.
> 
> Separately I do think we should look at the changes in https://github.com/wasmCloud/wasmcloud.com/pull/374 and get those merged in, there's a lot of good work being done there.

Thank you and I agree. If we get a linting workflow we can get that PR integrated.

**Comment by CazJT** [comment]
Just catching up on his. A lot of this is stylistic and so, I guess it would be useful to analyse the output and identify how you would like written work to feel ongoing. I will sync with Lachlan to discuss.

Would also like to understand if this is easy for me to use, as an author of Cosmonic content. I can't use spell check right now because of the way my laptop is set up.

**Review by thomastaylor312 — CHANGES_REQUESTED** [review]
I would like to have more of a discussion about this before adopting it

**Comment by thomastaylor312** [comment]
I do want to make sure I understand the plan here though. Is the plan to add this as an extension to Vale that we maintain/consume, rather than a 3rd party bot?

**Comment by joonas** [comment]
> I do want to make sure I understand the plan here though. Is the plan to add this as an extension to Vale that we maintain/consume, rather than a 3rd party bot?

That is the plan as I understand it

**Pull request closed without merging**
