### PR TITLE
Frontpage restyle with new scribbles

### PR DESCRIPTION
**Pull request by boomskats**
## Feature or Problem

A new look for the front page and a few style tweaks to the docusaurus template

## Related Issues
n/a 

## Release Information
n/a

## Consumer Impact
n/a

## Testing
`npm run build`, `npm run serve`, visual check of prod build

### Unit Test(s)
n/a

### Acceptance or Integration
n/a

### Manual Verification
As above, `npm run build`, `npm run serve`, visual check of prod build

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
@boomskats taking a look! Just wanted to let you know early that, being a CNCF project, we require signed off commits as a part of the DCO check. https://github.com/wasmCloud/wasmcloud.com/pull/283/checks?check_run_id=21068152936 should give you the easy rebase command to do this, it's just an admonition in the commit with your github ID no GPG required.

It also looks like there is a conflict in `src/css/custom.css` that needs resolution

**Comment by boomskats** [comment]
Thanks @brooksmtownsend, that should all be fixed up now. If you want any more info on why `postcss-preset-env` have a look at the issue [here](https://github.com/facebook/docusaurus/issues/9303#issuecomment-1733573738).

**Comment by lachieh** [comment]
@boomskats this is looking great! Really appreciate the time you put in here.

I apologise for not having better documenation/automation around this but it looks like there's a few formatting changes. Could you run `prettier -w {filename}` on the changed files? It looks like it's only js/ts files. If you're on mac/linux you should be able to run this to do all the files in one go:
```bash
git diff --name-only origin/main | grep "js\|ts" | xargs npx prettier -w
```

**Comment by boomskats** [comment]
> @boomskats this is looking great! Really appreciate the time you put in here.
> 
> I apologise for not having better documenation/automation around this but it looks like there's a few formatting changes. Could you run `prettier -w {filename}` on the changed files? It looks like it's only js/ts files. If you're on mac/linux you should be able to run this to do all the files in one go:
> 
> ```shell
> git diff --name-only origin/main | grep "js\|ts" | xargs npx prettier -w
> ```

Yeah it's a bit of a monster to eyeball, I didn't quite expect that! Does this give you what you're looking for?

```shell
 wasmcloud.com on  frontpage-restyle [$!] via  v20.10.0
❯ git diff --name-only --diff-filter=MA main | grep 'js$\|ts$\|css$' | xargs npx prettier -w
docusaurus.config.ts 202ms (unchanged)
src/components/HomepageFeatures/index.js 47ms (unchanged)
src/components/HomepageFeatures/styles.module.css 31ms (unchanged)
src/components/NewsSection/index.js 8ms (unchanged)
src/components/NewsSection/styles.module.css 12ms (unchanged)
src/css/custom.css 11ms (unchanged)
src/pages/index.js 11ms (unchanged)
src/pages/index.module.css 16ms (unchanged)

wasmcloud.com on  frontpage-restyle [$!] via  v20.10.0 took 2s
```

**Review by brooksmtownsend — APPROVED** [review]
Looks amazing to me! Leaving the merge to @lachieh once he's happy with formatting

**Review by lachieh — APPROVED** [review]
No idea why the output says unchanged for all those files, but it looks good now!

Thanks! Let's get it merged!

**Comment by connorsmith256** [comment]
@boomskats this looks amazing, thank you so much ❤️

**Comment by lachieh** [comment]
Had to do a bit of conflict resolution in the rebase locally so I'm going to close this and all these changes will get merged in #286.

Thanks, again!

**Pull request closed without merging**
