### PR TITLE
Adding capital one (sponsor) logo

### PR DESCRIPTION
**Pull request by autodidaddict**
In the preview I have, the "swoosh" part of capital one's logo gets a little cut off, but I can't really find one that's smaller. I've made a number of attempts at manually injecting padding into the image so that the swoosh doesn't get cut off, but this is really beyond my abilities.

The official logo art image does this same thing. I was thinking if you put the image inside a taller image, so that when it gets compressed for the sponsor bar, it wouldn't get cut off, but alas that didn't work.

### CODE REVIEW

**Comment by LiamRandall** [comment]
I updated the logo @autodidaddict so that it shows up correctly on the sponsor bar.

**Comment by autodidaddict** [comment]
> I updated the logo @autodidaddict so that it shows up correctly on the sponsor bar.

Thank you for your fabulous design skillz.

**Comment by autodidaddict** [comment]
If that's all set please approve

**Comment by LiamRandall** [comment]
Lgtm.

**Comment by LiamRandall** [comment]
Because I was the last commit, I think you need to approve. @autodidaddict

**Comment by autodidaddict** [comment]
You're the reviewer.

**Comment by autodidaddict** [comment]
image

**Review by LiamRandall — COMMENTED** [review]
Updated logo now looks correct to me.

**Review by LiamRandall — APPROVED** [review]
lgtm

**Pull request merged**
