### PR TITLE
chore: improve a11y

### PR DESCRIPTION
**Pull request by yordis**
I fixed a few issues using the `axe DevTools` reporting tool.

image

### CODE REVIEW

**Comment by yordis** [comment]
I fixed few colors in the light theme:

Screenshot 2023-09-23 at 2 36 05 AM
Screenshot 2023-09-23 at 2 58 34 AM

**Comment by lachieh** [comment]
Love it. Thank you!

**Review by lachieh — APPROVED** [review]
This looks good as is, but if you'd like, I think the menu links (and possibly all anchor elements) are also out of spec for a11y.

**Comment by yordis** [comment]
The header is accessible, just not AA, only A

**Review by brooksmtownsend — APPROVED** [review]

**Comment by lachieh** [comment]
Thanks, @yordis!

**Pull request merged**
